// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/anyproto/any-sync-coordinator/deletionlog (interfaces: DeletionLog)
//
// Generated by this command:
//
//	mockgen -destination mock_deletionlog/mock_deletionlog.go github.com/anyproto/any-sync-coordinator/deletionlog DeletionLog
//

// Package mock_deletionlog is a generated GoMock package.
package mock_deletionlog

import (
	context "context"
	reflect "reflect"

	deletionlog "github.com/anyproto/any-sync-coordinator/deletionlog"
	app "github.com/anyproto/any-sync/app"
	gomock "go.uber.org/mock/gomock"
)

// MockDeletionLog is a mock of DeletionLog interface.
type MockDeletionLog struct {
	ctrl     *gomock.Controller
	recorder *MockDeletionLogMockRecorder
	isgomock struct{}
}

// MockDeletionLogMockRecorder is the mock recorder for MockDeletionLog.
type MockDeletionLogMockRecorder struct {
	mock *MockDeletionLog
}

// NewMockDeletionLog creates a new mock instance.
func NewMockDeletionLog(ctrl *gomock.Controller) *MockDeletionLog {
	mock := &MockDeletionLog{ctrl: ctrl}
	mock.recorder = &MockDeletionLogMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeletionLog) EXPECT() *MockDeletionLogMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockDeletionLog) Add(ctx context.Context, spaceId, fileGroup string, status deletionlog.Status) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, spaceId, fileGroup, status)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockDeletionLogMockRecorder) Add(ctx, spaceId, fileGroup, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockDeletionLog)(nil).Add), ctx, spaceId, fileGroup, status)
}

// AddOwnershipChange mocks base method.
func (m *MockDeletionLog) AddOwnershipChange(ctx context.Context, spaceId, aclRecordId string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOwnershipChange", ctx, spaceId, aclRecordId)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddOwnershipChange indicates an expected call of AddOwnershipChange.
func (mr *MockDeletionLogMockRecorder) AddOwnershipChange(ctx, spaceId, aclRecordId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOwnershipChange", reflect.TypeOf((*MockDeletionLog)(nil).AddOwnershipChange), ctx, spaceId, aclRecordId)
}

// Close mocks base method.
func (m *MockDeletionLog) Close(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDeletionLogMockRecorder) Close(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDeletionLog)(nil).Close), ctx)
}

// GetAfter mocks base method.
func (m *MockDeletionLog) GetAfter(ctx context.Context, afterId string, limit uint32) ([]deletionlog.Record, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAfter", ctx, afterId, limit)
	ret0, _ := ret[0].([]deletionlog.Record)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAfter indicates an expected call of GetAfter.
func (mr *MockDeletionLogMockRecorder) GetAfter(ctx, afterId, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAfter", reflect.TypeOf((*MockDeletionLog)(nil).GetAfter), ctx, afterId, limit)
}

// Init mocks base method.
func (m *MockDeletionLog) Init(a *app.App) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", a)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockDeletionLogMockRecorder) Init(a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockDeletionLog)(nil).Init), a)
}

// Name mocks base method.
func (m *MockDeletionLog) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockDeletionLogMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockDeletionLog)(nil).Name))
}

// Run mocks base method.
func (m *MockDeletionLog) Run(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockDeletionLogMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockDeletionLog)(nil).Run), ctx)
}
