// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/anyproto/any-sync-coordinator/invitestore (interfaces: InviteStore)
//
// Generated by this command:
//
//	mockgen -destination mock_invitestore/mock_invitestore.go github.com/anyproto/any-sync-coordinator/invitestore InviteStore
//

// Package mock_invitestore is a generated GoMock package.
package mock_invitestore

import (
	context "context"
	reflect "reflect"

	invitestore "github.com/anyproto/any-sync-coordinator/invitestore"
	app "github.com/anyproto/any-sync/app"
	gomock "go.uber.org/mock/gomock"
)

// MockInviteStore is a mock of InviteStore interface.
type MockInviteStore struct {
	ctrl     *gomock.Controller
	recorder *MockInviteStoreMockRecorder
	isgomock struct{}
}

// MockInviteStoreMockRecorder is the mock recorder for MockInviteStore.
type MockInviteStoreMockRecorder struct {
	mock *MockInviteStore
}

// NewMockInviteStore creates a new mock instance.
func NewMockInviteStore(ctrl *gomock.Controller) *MockInviteStore {
	mock := &MockInviteStore{ctrl: ctrl}
	mock.recorder = &MockInviteStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInviteStore) EXPECT() *MockInviteStoreMockRecorder {
	return m.recorder
}

// Bind mocks base method.
func (m *MockInviteStore) Bind(ctx context.Context, entry invitestore.Entry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bind", ctx, entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// Bind indicates an expected call of Bind.
func (mr *MockInviteStoreMockRecorder) Bind(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bind", reflect.TypeOf((*MockInviteStore)(nil).Bind), ctx, entry)
}

// Close mocks base method.
func (m *MockInviteStore) Close(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockInviteStoreMockRecorder) Close(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockInviteStore)(nil).Close), ctx)
}

// Delete mocks base method.
func (m *MockInviteStore) Delete(ctx context.Context, cid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, cid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockInviteStoreMockRecorder) Delete(ctx, cid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockInviteStore)(nil).Delete), ctx, cid)
}

// Get mocks base method.
func (m *MockInviteStore) Get(ctx context.Context, cid string) (invitestore.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, cid)
	ret0, _ := ret[0].(invitestore.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockInviteStoreMockRecorder) Get(ctx, cid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockInviteStore)(nil).Get), ctx, cid)
}

// Init mocks base method.
func (m *MockInviteStore) Init(a *app.App) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", a)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockInviteStoreMockRecorder) Init(a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockInviteStore)(nil).Init), a)
}

// Name mocks base method.
func (m *MockInviteStore) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockInviteStoreMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockInviteStore)(nil).Name))
}

// Run mocks base method.
func (m *MockInviteStore) Run(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockInviteStoreMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockInviteStore)(nil).Run), ctx)
}
