// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/anyproto/any-sync-coordinator/coordinatorlog (interfaces: CoordinatorLog)
//
// Generated by this command:
//
//	mockgen -destination mock_coordinatorlog/mock_coordinatorlog.go github.com/anyproto/any-sync-coordinator/coordinatorlog CoordinatorLog
//

// Package mock_coordinatorlog is a generated GoMock package.
package mock_coordinatorlog

import (
	context "context"
	reflect "reflect"

	coordinatorlog "github.com/anyproto/any-sync-coordinator/coordinatorlog"
	app "github.com/anyproto/any-sync/app"
	gomock "go.uber.org/mock/gomock"
)

// MockCoordinatorLog is a mock of CoordinatorLog interface.
type MockCoordinatorLog struct {
	ctrl     *gomock.Controller
	recorder *MockCoordinatorLogMockRecorder
}

// MockCoordinatorLogMockRecorder is the mock recorder for MockCoordinatorLog.
type MockCoordinatorLogMockRecorder struct {
	mock *MockCoordinatorLog
}

// NewMockCoordinatorLog creates a new mock instance.
func NewMockCoordinatorLog(ctrl *gomock.Controller) *MockCoordinatorLog {
	mock := &MockCoordinatorLog{ctrl: ctrl}
	mock.recorder = &MockCoordinatorLogMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCoordinatorLog) EXPECT() *MockCoordinatorLogMockRecorder {
	return m.recorder
}

// AddLog mocks base method.
func (m *MockCoordinatorLog) AddLog(arg0 context.Context, arg1 coordinatorlog.SpaceUpdateEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddLog", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddLog indicates an expected call of AddLog.
func (mr *MockCoordinatorLogMockRecorder) AddLog(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLog", reflect.TypeOf((*MockCoordinatorLog)(nil).AddLog), arg0, arg1)
}

// GetAfter mocks base method.
func (m *MockCoordinatorLog) GetAfter(arg0 context.Context, arg1, arg2 string, arg3 uint32) ([]coordinatorlog.SpaceUpdateEntry, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAfter", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]coordinatorlog.SpaceUpdateEntry)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAfter indicates an expected call of GetAfter.
func (mr *MockCoordinatorLogMockRecorder) GetAfter(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAfter", reflect.TypeOf((*MockCoordinatorLog)(nil).GetAfter), arg0, arg1, arg2, arg3)
}

// Init mocks base method.
func (m *MockCoordinatorLog) Init(arg0 *app.App) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockCoordinatorLogMockRecorder) Init(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockCoordinatorLog)(nil).Init), arg0)
}

// Name mocks base method.
func (m *MockCoordinatorLog) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockCoordinatorLogMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockCoordinatorLog)(nil).Name))
}
