// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/anyproto/any-sync-coordinator/fileusage (interfaces: FileUsage)
//
// Generated by this command:
//
//	mockgen -destination mock_fileusage/mock_fileusage.go github.com/anyproto/any-sync-coordinator/fileusage FileUsage
//

// Package mock_fileusage is a generated GoMock package.
package mock_fileusage

import (
	context "context"
	reflect "reflect"

	app "github.com/anyproto/any-sync/app"
	coordinatorproto "github.com/anyproto/any-sync/coordinator/coordinatorproto"
	gomock "go.uber.org/mock/gomock"
)

// MockFileUsage is a mock of FileUsage interface.
type MockFileUsage struct {
	ctrl     *gomock.Controller
	recorder *MockFileUsageMockRecorder
	isgomock struct{}
}

// MockFileUsageMockRecorder is the mock recorder for MockFileUsage.
type MockFileUsageMockRecorder struct {
	mock *MockFileUsage
}

// NewMockFileUsage creates a new mock instance.
func NewMockFileUsage(ctrl *gomock.Controller) *MockFileUsage {
	mock := &MockFileUsage{ctrl: ctrl}
	mock.recorder = &MockFileUsageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileUsage) EXPECT() *MockFileUsageMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockFileUsage) Close(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockFileUsageMockRecorder) Close(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockFileUsage)(nil).Close), ctx)
}

// GetLimits mocks base method.
func (m *MockFileUsage) GetLimits(ctx context.Context, spaceId, identity string) (*coordinatorproto.FileLimitsGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLimits", ctx, spaceId, identity)
	ret0, _ := ret[0].(*coordinatorproto.FileLimitsGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLimits indicates an expected call of GetLimits.
func (mr *MockFileUsageMockRecorder) GetLimits(ctx, spaceId, identity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLimits", reflect.TypeOf((*MockFileUsage)(nil).GetLimits), ctx, spaceId, identity)
}

// Init mocks base method.
func (m *MockFileUsage) Init(a *app.App) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", a)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockFileUsageMockRecorder) Init(a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockFileUsage)(nil).Init), a)
}

// Name mocks base method.
func (m *MockFileUsage) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockFileUsageMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockFileUsage)(nil).Name))
}

// Report mocks base method.
func (m *MockFileUsage) Report(ctx context.Context, nodeId string, rows []*coordinatorproto.FileUsageRow) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Report", ctx, nodeId, rows)
	ret0, _ := ret[0].(error)
	return ret0
}

// Report indicates an expected call of Report.
func (mr *MockFileUsageMockRecorder) Report(ctx, nodeId, rows any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Report", reflect.TypeOf((*MockFileUsage)(nil).Report), ctx, nodeId, rows)
}

// Run mocks base method.
func (m *MockFileUsage) Run(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockFileUsageMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockFileUsage)(nil).Run), ctx)
}
